// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UerRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UerRequest) Reset()         { *m = UerRequest{} }
func (m *UerRequest) String() string { return proto.CompactTextString(m) }
func (*UerRequest) ProtoMessage()    {}
func (*UerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *UerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UerRequest.Unmarshal(m, b)
}
func (m *UerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UerRequest.Marshal(b, m, deterministic)
}
func (m *UerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UerRequest.Merge(m, src)
}
func (m *UerRequest) XXX_Size() int {
	return xxx_messageInfo_UerRequest.Size(m)
}
func (m *UerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UerRequest proto.InternalMessageInfo

func (m *UerRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type UerResponse struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Age                  int32    `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	Hobby                []string `protobuf:"bytes,4,rep,name=hobby,proto3" json:"hobby,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UerResponse) Reset()         { *m = UerResponse{} }
func (m *UerResponse) String() string { return proto.CompactTextString(m) }
func (*UerResponse) ProtoMessage()    {}
func (*UerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *UerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UerResponse.Unmarshal(m, b)
}
func (m *UerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UerResponse.Marshal(b, m, deterministic)
}
func (m *UerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UerResponse.Merge(m, src)
}
func (m *UerResponse) XXX_Size() int {
	return xxx_messageInfo_UerResponse.Size(m)
}
func (m *UerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UerResponse proto.InternalMessageInfo

func (m *UerResponse) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UerResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UerResponse) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *UerResponse) GetHobby() []string {
	if m != nil {
		return m.Hobby
	}
	return nil
}

func init() {
	proto.RegisterType((*UerRequest)(nil), "proto.UerRequest")
	proto.RegisterType((*UerResponse)(nil), "proto.UerResponse")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 179 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x2d, 0x4e, 0x2d,
	0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0x0a, 0x5c, 0x5c, 0xa1, 0xa9,
	0x45, 0x41, 0xa9, 0x85, 0xa5, 0xa9, 0xc5, 0x25, 0x42, 0x42, 0x5c, 0x2c, 0x79, 0x89, 0xb9, 0xa9,
	0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x60, 0xb6, 0x52, 0x24, 0x17, 0x37, 0x58, 0x45, 0x71,
	0x41, 0x7e, 0x5e, 0x71, 0xaa, 0x10, 0x1f, 0x17, 0x53, 0x66, 0x0a, 0x58, 0x01, 0x6b, 0x10, 0x53,
	0x66, 0x0a, 0x5c, 0x0b, 0x13, 0x42, 0x8b, 0x90, 0x00, 0x17, 0x73, 0x62, 0x7a, 0xaa, 0x04, 0x33,
	0x58, 0x11, 0x88, 0x29, 0x24, 0xc2, 0xc5, 0x9a, 0x91, 0x9f, 0x94, 0x54, 0x29, 0xc1, 0xa2, 0xc0,
	0xac, 0xc1, 0x19, 0x04, 0xe1, 0x18, 0x79, 0x72, 0xf1, 0x87, 0x16, 0xa7, 0x16, 0x79, 0xe6, 0xa5,
	0xe5, 0x07, 0xa7, 0x16, 0x95, 0x65, 0x26, 0xa7, 0x0a, 0x99, 0x71, 0x71, 0xbb, 0xa7, 0x96, 0xc0,
	0x44, 0x85, 0x04, 0x21, 0xae, 0xd5, 0x43, 0xb8, 0x51, 0x4a, 0x08, 0x59, 0x08, 0xe2, 0x28, 0x25,
	0x86, 0x24, 0x36, 0xb0, 0xa0, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x0e, 0x86, 0x9a, 0xa5, 0xe3,
	0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserInfoServiceClient is the client API for UserInfoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserInfoServiceClient interface {
	GetUserInfo(ctx context.Context, in *UerRequest, opts ...grpc.CallOption) (*UerResponse, error)
}

type userInfoServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserInfoServiceClient(cc *grpc.ClientConn) UserInfoServiceClient {
	return &userInfoServiceClient{cc}
}

func (c *userInfoServiceClient) GetUserInfo(ctx context.Context, in *UerRequest, opts ...grpc.CallOption) (*UerResponse, error) {
	out := new(UerResponse)
	err := c.cc.Invoke(ctx, "/proto.UserInfoService/GetUserInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserInfoServiceServer is the server API for UserInfoService service.
type UserInfoServiceServer interface {
	GetUserInfo(context.Context, *UerRequest) (*UerResponse, error)
}

// UnimplementedUserInfoServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUserInfoServiceServer struct {
}

func (*UnimplementedUserInfoServiceServer) GetUserInfo(ctx context.Context, req *UerRequest) (*UerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserInfo not implemented")
}

func RegisterUserInfoServiceServer(s *grpc.Server, srv UserInfoServiceServer) {
	s.RegisterService(&_UserInfoService_serviceDesc, srv)
}

func _UserInfoService_GetUserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserInfoServiceServer).GetUserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.UserInfoService/GetUserInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserInfoServiceServer).GetUserInfo(ctx, req.(*UerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserInfoService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.UserInfoService",
	HandlerType: (*UserInfoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserInfo",
			Handler:    _UserInfoService_GetUserInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
